// AUTO-GENERATED BY A SCRIPT, DON'T TOUCH

import './ready'
import './cureRequired'
import './index'
import './messageCreate/messageScanRequired'
import './messageReactionAdd/correctResponse'
import './interactionCreate/chatCommand'
import './interactionCreate/correctResponse'
import './guildMemberAdd/applyRolePresets'
